"""Summarizer agent.

Computes the merge-gate decision deterministically (so the gate is auditable and
never depends on a flaky model), then renders the human-facing PR comment in
Markdown. The LLM contributes only a one-line headline; the gate and the body are
pure functions of the findings.
"""

from __future__ import annotations

from app.config import get_settings
from app.llm import chat_json
from app.models import FixSuggestion, GraphState, TriagedIssue

HEADLINE_SYSTEM = (
    "You write a single-sentence headline summarizing a code-quality gate result "
    "for a pull request. Be factual and concise. Respond as JSON: {\"headline\": \"...\"}."
)


def _decide_gate(triaged: list[TriagedIssue], security: list[TriagedIssue]) -> tuple[str, str]:
    blocking = get_settings().blocking_severities
    blockers = [t for t in triaged if t.issue.severity in blocking]
    vulns = [t for t in security if t.issue.type == "VULNERABILITY"]

    if blockers or vulns:
        bits = []
        if blockers:
            bits.append(f"{len(blockers)} blocking issue(s) ({'/'.join(blocking)})")
        if vulns:
            bits.append(f"{len(vulns)} open vulnerability(ies)")
        return "FAIL", "Gate failed: " + " and ".join(bits) + "."
    return "PASS", "Gate passed: no blocking issues or open vulnerabilities."


def _render_markdown(
    project: str,
    gate: str,
    reason: str,
    headline: str,
    triaged: list[TriagedIssue],
    security: list[TriagedIssue],
    fixes: list[FixSuggestion],
) -> str:
    emoji = "✅" if gate == "PASS" else "❌"
    lines = [
        f"## {emoji} GateKeeper — {gate}",
        "",
        f"**{headline}**",
        "",
        f"_{reason}_",
        "",
        f"**Project:** `{project}` &nbsp;&nbsp; **Findings:** {len(triaged)} open "
        f"&nbsp;&nbsp; **Security:** {len(security)}",
        "",
    ]

    if triaged:
        lines += [
            "### Top findings",
            "",
            "| Priority | Severity | Type | Location | Why it matters |",
            "|---|---|---|---|---|",
        ]
        for t in triaged[:10]:
            loc = (
                f"`{t.issue.component}:{t.issue.line}`"
                if t.issue.line
                else f"`{t.issue.component}`"
            )
            lines.append(
                f"| {t.priority} | {t.issue.severity} | {t.issue.type} | {loc} | {t.rationale} |"
            )
        lines.append("")

    if fixes:
        lines += ["### Suggested fixes", ""]
        for f in fixes:
            lines += [
                f"<details><summary><code>{f.component}</code> — {f.summary}</summary>",
                "",
                "```diff",
                f.patch,
                "```",
                "</details>",
                "",
            ]

    lines += [
        "---",
        "<sub>Generated by GateKeeper — SonarQube findings triaged by a "
        "LangGraph multi-agent system.</sub>",
    ]
    return "\n".join(lines)


def summarizer_node(state: GraphState) -> GraphState:
    settings = get_settings()
    report = state["report"]
    triaged: list[TriagedIssue] = state.get("triaged", [])
    security: list[TriagedIssue] = state.get("security_findings", [])
    fixes: list[FixSuggestion] = state.get("fix_suggestions", [])

    gate, reason = _decide_gate(triaged, security)

    headline = reason
    if not settings.use_mock:
        data = chat_json(
            HEADLINE_SYSTEM,
            f"Gate: {gate}. {reason} Project {report.project} has {len(triaged)} open findings.",
            settings.model_summary,
        )
        headline = data.get("headline") or reason

    summary_markdown = _render_markdown(
        report.project, gate, reason, headline, triaged, security, fixes
    )
    return {"gate": gate, "reason": reason, "summary_markdown": summary_markdown}
